# Generated by Django 4.2.1 on 2023-05-23 08:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_profile_birth_date_profile_genres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instruments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), default=list, size=None),
        ),
    ]
